### ISSUE TITLE
[docs] ReadTheDocs ownership and setup 

### ISSUE THREAD

**Issue by JonathanHuot** [oauthlib/oauthlib#516]
It seems that RTD build is failing since few months, and totally stopped since the project migration to the community.

To continue the build, we need @idan to add additional maintainers or transfer the ownership to the current team. Or at least, change the URL to the new community project.

The URL to add maintainer should be https://readthedocs.org/dashboard/oauthlib/users/

**Comment by skion** [comment]
@idan @thedrow Either of you have access to [ReadTheDocs](https://readthedocs.org/projects/oauthlib/builds/)? We'd like to sync the docs before releasing a new version.

**Comment by thedrow** [comment]
Only @idan has it unfortunately.

**Comment by skion** [comment]
@thedrow We could write to RTD to initiate the (six-week) procedure for an [abandoned project](https://docs.readthedocs.io/en/latest/abandoned-projects.html). The only hurdle I see there is the "The project has fewer than 100 monthly pageviews" requirement, which we probably don't meet. Would be great if @idan can just pass it on...

**Comment by idan** [comment]
@thedrow what's your RTD user so I can add you as an admin?

URLs redirected already

**Comment by JonathanHuot** [comment]
@idan : from his github's profile, it should be omer.drow@gmail.com ! Thanks !

**Comment by idan** [comment]
@JonathanHuot @thedrow nope, emails don't work, I need a RTD user name

**Comment by idan** [comment]
@thedrow done

**Comment by thedrow** [comment]
Thanks @idan!

The build is failing because of the following traceback:
```
Running Sphinx v1.6.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/oauthlib/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oauthlib/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oauthlib/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oauthlib/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/oauthlib/envs/latest/local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 17, in <module>
    from oauthlib import __version__ as v
ImportError: No module named oauthlib

Exception occurred:
  File "conf.py", line 17, in <module>
    from oauthlib import __version__ as v
ImportError: No module named oauthlib
The full traceback has been saved in /tmp/sphinx-err-fx4NAK.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by JonathanHuot** [comment]
Should be fixed at https://github.com/oauthlib/oauthlib/pull/521. Waiting for the confirmation (merging) before closing this issue.
