### ISSUE TITLE
Raising an exception on scope mismatch is too strict

### ISSUE THREAD

**Issue by liiight** [oauthlib/oauthlib#562]
The following use case described Office Graph API authentication flow. MS uses the `offline_access` scope as a flag that a refresh token should be provided with the access token: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth#authentication-scopes

When authenticating though, it does not return that particular scope in the response, resulting in an exception:
```python
scopes = "offline_access Files.ReadWrite.All User.Read Group.ReadWrite.All Sites.ReadWrite.All Directory.ReadWrite.All Mail.Read User.ReadWrite.All"

oauth = OAuth2Session(client_id, redirect_uri=redirect_url, scope=scopes)
authorization_url, state = oauth.authorization_url(
    url=auth_url,
    response_mode='query',
    state='12345'
)
webbrowser.open_new(authorization_url)

auth_response = input('Response url')

token = oauth.fetch_token(
    token_url,
    authorization_response=auth_response,
    client_secret=client_secret,
)
```
```text
Traceback (most recent call last):
  File "/Users/orcarmi/PycharmProjects/shield/oauth_porc.py", line 28, in <module>
    client_secret=client_secret,
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 409, in validate_token_parameters
    raise w
Warning: Scope has changed from "Directory.ReadWrite.All offline_access Mail.Read User.ReadWrite.All User.Read Files.ReadWrite.All Group.ReadWrite.All Sites.ReadWrite.All" to "Directory.ReadWrite.All Mail.Read User.ReadWrite.All User.Read Files.ReadWrite.All Group.ReadWrite.All Sites.ReadWrite.All".
```
According to the [RFC](https://tools.ietf.org/html/rfc6749#section-3.3), this is valid, since they return the updated `scope` in the response: 
>The authorization server MAY fully or partially ignore the scope
   requested by the client, based on the authorization server policy or
   the resource owner's instructions.  If the issued access token scope
   is different from the one requested by the client, the authorization
   server MUST include the "scope" response parameter to inform the
   client of the actual scope granted

The workaround for this is setting the `OAUTHLIB_RELAX_TOKEN_SCOPE` envar.

Perhaps an exception should be raised only if the response does not contain the `scope` parameter at all, which will violate the RFC.

**Comment by JonathanHuot** [comment]
After reviewing the initial author's intent, it seems @ib-lundgren at https://github.com/oauthlib/oauthlib/commit/ca4811b3087f9d34754d3debf839e247593b8a39 provided a way to access scope changes thru the `OAuth2Token`, and he also added this env var only for preserving behavior (IMHO). 

As he mentioned in his comment, ```Users who don't want to catch a warning can instead
check the boolean token property ``token.scope_changed``. Note
that the warning must first be disabled by setting the
environment variable ``OAUTHLIB_RELAX_TOKEN_SCOPE``.```

Thanks

I guess we can take the opportunity for 3.0.0 to remove this env-thing and provide a single way of accessing the scopes (the `OAuth2Token`).

However, I'm not fully aware of the client side of `oauthlib`. Maybe some comments from others ? also ping requests team: @singingwolfboy @jdufresne @lukasa

**Comment by liiight** [comment]
While not completely related to the issue at hand, there are some assumptions in the aforementioned `OAuth2Token` [object](https://github.com/oauthlib/oauthlib/blob/master/oauthlib/oauth2/rfc6749/tokens.py#L27) that are not necessarily true:

```python
class OAuth2Token(dict):

    def __init__(self, params, old_scope=None):
        super(OAuth2Token, self).__init__(params)
        self._new_scope = None
        if 'scope' in params and params['scope']:
            self._new_scope = set(utils.scope_to_list(params['scope']))
        if old_scope is not None:
            self._old_scope = set(utils.scope_to_list(old_scope))
            if self._new_scope is None:
                # the rfc says that if the scope hasn't changed, it's optional
                # in params so set the new scope to the old scope
                self._new_scope = self._old_scope
        else:
            self._old_scope = self._new_scope
```
1. The response is allowed not to contain the `scope` param ONLY if the scope hasn't changed, which is a provider decision. This code assumes that not passing the `scope` param means that it hasn't changed, and while that is probably the case most of the time, maybe a log warning is relevant here to note that.

2. If `self._old_scope` is `None`, implicitly setting it to the new scope (if it isn't `None` as well) should probably be treated with a similar warning as the previous bullet point.

**Comment by PrestonTaylor** [comment]
I have seen production systems which require you to request a refresh token in the scope and they then remove that scope in the reply. This is perfectly acceptable per the RFC and throwing an exception for it makes this library completely unusable unless I'm missing something.

**Comment by PrestonTaylor** [comment]
Still seeing this issue in Microsoft Graph. Is there any reason to discuss this beyond the RFC? env variables seems like a very clunky way of handling security settings.

**Comment by thedrow** [comment]
Contributions are always welcome :)

**Comment by duaneking** [comment]
If Microsoft chooses to implement the standard incorrectly, that's not on is to support them; they are a for-profit company with billions after all.
