### ISSUE TITLE
Scope has changed from "profile openid email" to "User.Read profile openid email"

### ISSUE THREAD

**Issue by LarryMartell** [oauthlib/oauthlib#732]
I am using the django_microsoft_auth package, which uses oauthlib. I am getting the error:

> Scope has changed from "profile openid email" to "User.Read profile openid email"

I found that that comes from validate_token_parameters and by commenting out the call to that the auth works. Obviously that is not a good solution. Any thoughts on this? 

Here is the stack trace:

```
Environment:

Request Method: POST
Request URL: https://xxxx.com/microsoft/auth-callback/

Django Version: 3.0.3
Python Version: 3.7.0
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.sites',
 'microsoft_auth',
 'app.dse',
 'core.reports',
 'ui']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'core.custom_exception_handling.CustomExceptionMiddleware',
 'ui.middleware.LastSiteUrl']



Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/microsoft_auth/views.py", line 47, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/microsoft_auth/views.py", line 145, in post
    context = self.get_context_data(**request.POST.dict())
  File "/usr/local/lib/python3.7/site-packages/microsoft_auth/views.py", line 68, in get_context_data
    self._authenticate(kwargs.get("code"))
  File "/usr/local/lib/python3.7/site-packages/microsoft_auth/views.py", line 129, in _authenticate
    user = authenticate(self.request, code=code)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.7/site-packages/microsoft_auth/backends.py", line 43, in authenticate
    token = self.microsoft.fetch_token(code=code)
  File "/usr/local/lib/python3.7/site-packages/microsoft_auth/client.py", line 172, in fetch_token
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 461, in validate_token_parameters
    raise w

Exception Type: Warning at /microsoft/auth-callback/
Exception Value: Scope has changed from "openid profile email" to "User.Read openid profile email".
```

**Comment by JeremyVriens** [comment]
Hello @LarryMartell , I don't think this is a bug in OAuthlib; looking at the microsoft_auth package, I did found something about this User.Read scope changes: https://github.com/AngellusMortis/django_microsoft_auth/blob/master/docs/usage.rst#sliencing-scope-has-changed-warnings. Maybe this helps you a bit (I can't help you further as I would need more context). As I mentioned, I don't think it's a bug on this project, so maybe we should close this ticket. Have a nice day!

**Comment by LarryMartell** [comment]
Setting that env var did not fix it for me. All the examples show setting it when using the django devel server. I am using nginx/uwsgi. I tried setting it for that, but it had no effect. As for the version, I am running the latest master - wouldn't that be version 2.x?

**Comment by thedrow** [comment]
Please file an issue upstream.
If it turns out to be a problem on our end we will reopen this issue.

**Comment by kevin-brown** [comment]
Here's a link to the upstream issue about this: https://github.com/AngellusMortis/django_microsoft_auth/issues/400
