### ISSUE TITLE
validate_token_parameters only checks for token in response body

### ISSUE THREAD

**Issue by georgavagyan** [oauthlib/oauthlib#805]
**Describe the bug**

If API returns JSON with `access_token` not in the top level, `validate_token_parameters()` fails to validate token and throws error.

**How to reproduce**

I got this error while working with Withings API, here's the link for response format (tl;dr - `access_token` is in the `body` key): 
https://support.withings.com//hc//en-us//articles//360016745358--BREAKING-Deprecating-access-and-refresh-tokens-endpoints
I called fetch_token method from requests_oauthlib, which internally calls validate_token_parameters() 

Stack trace with the problem:

```
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://wbsapi.withings.net/v2/oauth2 using method POST.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'authorization_code', 'client_id': 'my_client_id', 'client_secret': 'my_client_secret', 'code': 'my_code', 'redirect_uri': 'http://127.0.0.1:8081/', 'action': 'requesttoken'}
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'timeout': None, 'auth': None, 'verify': True, 'proxies': None, 'cert': None}.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): wbsapi.withings.net:443
DEBUG:urllib3.connectionpool:https://wbsapi.withings.net:443 "POST /v2/oauth2 HTTP/1.1" 200 263
DEBUG:requests_oauthlib.oauth2_session:Request to fetch token completed with status 200.
DEBUG:requests_oauthlib.oauth2_session:Request url was https://wbsapi.withings.net/v2/oauth2
DEBUG:requests_oauthlib.oauth2_session:Request headers were {'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '295'}
DEBUG:requests_oauthlib.oauth2_session:Request body was grant_type=authorization_code&client_id=my_client_id&client_secret=my_client_secret&code=my_code&redirect_uri=http%3A%2F%2F127.0.0.1%3A8081%2F&action=requesttoken
DEBUG:requests_oauthlib.oauth2_session:Response headers were {'date': 'Tue, 15 Feb 2022 10:55:22 GMT', 'server': 'Apache', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET, POST, OPTIONS', 'access-control-allow-headers': 'Content-Type, *', 'content-length': '263', 'content-type': 'application/json'} **and content {"status":0,"body":{"userid":"19047203","access_token":"4dc24d85ae5d50675aa90430a599779a1d88b4ae","refresh_token":"23f8152c636868fa206a73e373e896b1c39dc699","scope":"user.info,user.metrics,user.activity,user.sleepevents","expires_in":10800,"token_type":"Bearer"}}.**
DEBUG:requests_oauthlib.oauth2_session:Invoking 0 token response hooks.
Traceback (most recent call last):
  File "/home/.../first_time_token.py", line 203, in <module>
    get_token(client)
  File "/home/.../first_time_token.py", line 183, in get_token
    if client.init_client():
  File "/home/.../first_time_token.py", line 110, in init_client
    response = self._client.fetch_token(
  File "/home/.../venv/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/home/.../venv/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 448, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/home/.../venv/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/home/.../venv/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 451, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

**Expected behavior**
As you can see from stack trace above, `fetch_token()` works fine on its own and **token is actually received**, but validation fails because of unusual response format.
It'll be nice to have an opportunity to omit this validation at all, if needed

**Additional context**

Please provide any further context here.

- I'm using OAuth1
- I'm writing server side code
- I'm using a downstream library `requests-oauthlib`

**Comment by georgavagyan** [comment]
Sorry, just realized that i can simply use `register_compliance_hook()` to tinker the response before parsing
