### ISSUE TITLE
3.2.0 caused "NotImplementedError: Subclasses must implement this method." error

### ISSUE THREAD

**Issue by krzysieqq** [oauthlib/oauthlib#813]
**Describe the bug**

I have problem using django-oauth-toolkit. I have app with setup:
client type - Confidential
grant type -  Authorization code
Skip authorization - True
Algorithm - HMAC with SHA-2 256

I tried to login with OIDC using on other side mozilla-django-oidc==2.0.0 and requests-oauthlib==1.3.1 after correct request goes to /authorize it throws 500. I think problem could be somewhere in cookies, because when i clear all data or go into incognito mode everything is ok. I tried to debug it but without any success. Maybe anyone have idea how to solve it?

**Additional context**

Please provide any further context here.

- Are you using OAuth1, OAuth2 or OIDC? - OIDC
- Are you writing client or server side code? - server side
- If client, what provider are you connecting to?
- Are you using a downstream library, such as `requests-oauthlib`, `django-oauth-toolkit`, ...? - django-oauth-toolkit==1.7.1, 

**Traceback**
```
backend_1  | Internal Server Error: /o/authorize/
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
backend_1  |     response = get_response(request)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
backend_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
backend_1  |     return callback(request, *args, **kwargs)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
backend_1  |     return self.dispatch(request, *args, **kwargs)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauth2_provider/views/base.py", line 41, in dispatch
backend_1  |     return super().dispatch(request, *args, **kwargs)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
backend_1  |     return super().dispatch(request, *args, **kwargs)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
backend_1  |     return handler(request, *args, **kwargs)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauth2_provider/views/base.py", line 145, in get
backend_1  |     scopes, credentials = self.validate_authorization_request(request)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauth2_provider/views/mixins.py", line 98, in validate_authorization_request
backend_1  |     return core.validate_authorization_request(request)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauth2_provider/oauth2_backends.py", line 101, in validate_authorization_request
backend_1  |     scopes, credentials = self.server.validate_authorization_request(
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 112, in wrapper
backend_1  |     return f(endpoint, uri, *args, **kwargs)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/endpoints/authorization.py", line 114, in validate_authorization_request
backend_1  |     return response_type_handler.validate_authorization_request(request)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauthlib/openid/connect/core/grant_types/dispatchers.py", line 37, in validate_authorization_request
backend_1  |     return self._handler_for_request(request).validate_authorization_request(request)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauthlib/openid/connect/core/grant_types/base.py", line 35, in validate_authorization_request
backend_1  |     return self.proxy_target.validate_authorization_request(request)
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/grant_types/authorization_code.py", line 432, in validate_authorization_request
backend_1  |     request_info.update(validator(request))
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauthlib/openid/connect/core/grant_types/base.py", line 301, in openid_authorization_validator
backend_1  |     if not self.request_validator.validate_silent_login(request):
backend_1  |   File "/usr/local/lib/python3.10/site-packages/oauthlib/openid/connect/core/request_validator.py", line 246, in validate_silent_login
backend_1  |     raise NotImplementedError('Subclasses must implement this method.')
backend_1  | NotImplementedError: Subclasses must implement this method.

```

**Comment by JonathanHuot** [comment]
Hi @krzysieqq, you will need to report the issue to django-oauth-toolkit I'm afraid.
It seems `validate_silent_login` function is not implemented in the `RequestValidator`.
