### ISSUE TITLE
test_rsa_bad_keys test fails with JWT 2.9.0

### ISSUE THREAD

**Issue by glaubitz** [oauthlib/oauthlib#877]
After updating JWT to 2.9.0, the test `test_rsa_bad_keys` fails with the following error:

```
[   15s] ======================================================================
[   15s] ERROR: test_rsa_bad_keys (tests.oauth1.rfc5849.test_signatures.SignatureTests)
[   15s] Testing RSA sign and verify with bad key values produces errors.
[   15s] ----------------------------------------------------------------------
[   15s] Traceback (most recent call last):
[   15s]   File "/usr/lib/python3.10/site-packages/jwt/algorithms.py", line 343, in prepare_key
[   15s]     RSAPrivateKey, load_pem_private_key(key_bytes, password=None)
[   15s] ValueError: ('Could not deserialize key data. The data may be in an incorrect format, the provided password may be incorrect, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=503841036, lib=60, reason=524556, reason_text=unsupported)>])
[   15s] 
[   15s] During handling of the above exception, another exception occurred:
[   15s] 
[   15s] Traceback (most recent call last):
[   15s]   File "/usr/lib/python3.10/site-packages/jwt/algorithms.py", line 347, in prepare_key
[   15s]     return cast(RSAPublicKey, load_pem_public_key(key_bytes))
[   15s] ValueError: Unable to load PEM file. See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file for more details. MalformedFraming
[   15s] 
[   15s] During handling of the above exception, another exception occurred:
[   15s] 
[   15s] Traceback (most recent call last):
[   15s]   File "/home/abuild/rpmbuild/BUILD/oauthlib-3.2.2/tests/oauth1/rfc5849/test_signatures.py", line 768, in test_rsa_bad_keys
[   15s]     self.assertRaises(ValueError,
[   15s]   File "/usr/lib64/python3.10/unittest/case.py", line 738, in assertRaises
[   15s]     return context.handle('assertRaises', args, kwargs)
[   15s]   File "/usr/lib64/python3.10/unittest/case.py", line 201, in handle
[   15s]     callable_obj(*args, **kwargs)
[   15s]   File "/home/abuild/rpmbuild/BUILD/oauthlib-3.2.2/oauthlib/oauth1/rfc5849/signature.py", line 751, in sign_rsa_sha1_with_client
[   15s]     return _sign_rsa('SHA-1', sig_base_str, client.rsa_key)
[   15s]   File "/home/abuild/rpmbuild/BUILD/oauthlib-3.2.2/oauthlib/oauth1/rfc5849/signature.py", line 646, in _sign_rsa
[   15s]     key = _prepare_key_plus(alg, rsa_private_key)
[   15s]   File "/home/abuild/rpmbuild/BUILD/oauthlib-3.2.2/oauthlib/oauth1/rfc5849/signature.py", line 595, in _prepare_key_plus
[   15s]     return alg.prepare_key(keystr)
[   15s]   File "/usr/lib/python3.10/site-packages/jwt/algorithms.py", line 349, in prepare_key
[   15s]     raise InvalidKeyError("Could not parse the provided public key.")
[   15s] jwt.exceptions.InvalidKeyError: Could not parse the provided public key.
[   15s] 
[   15s] ----------------------------------------------------------------------
[   15s] Ran 654 tests in 2.261s
```

**Comment by heirecka** [comment]
I don't see this anymore after https://github.com/oauthlib/oauthlib/pull/878
